#!/usr/bin/env node
/**
 * Ratchet gate for Electron imports in src/main/.
 *
 * This scans non-test modules under src/main/ for direct imports of `electron`
 * and compares them against config/shell-electron-baseline.txt.
 *
 * A NEW file importing electron fails CI.
 * A REMOVED file importing electron must be updated via --write so the ceiling ratchets down.
 *
 * Usage: node config/scripts/check-shell-electron-ratchet.ts [--write]
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { pathToFileURL } from 'node:url'

const ROOT = path.join(import.meta.dirname, '..', '..')
const BASELINE_PATH = path.join(ROOT, 'config', 'shell-electron-baseline.txt')

const ELECTRON_IMPORT_PATTERN =
  /(?:from\s+['"]electron(?:\/.*)?['"]|require\(['"]electron(?:\/.*)?['"]\))/

export function scanShellElectronImporters(dir = path.join(ROOT, 'src', 'main')): string[] {
  const importers: string[] = []

  function walk(currentDir: string): void {
    for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
      const fullPath = path.join(currentDir, entry.name)
      if (entry.isDirectory()) {
        walk(fullPath)
      } else if (
        entry.isFile() &&
        (fullPath.endsWith('.ts') ||
          fullPath.endsWith('.tsx') ||
          fullPath.endsWith('.js') ||
          fullPath.endsWith('.mjs')) &&
        !fullPath.includes('.test.') &&
        !fullPath.includes('__fixtures__')
      ) {
        const content = readFileSync(fullPath, 'utf8')
        if (ELECTRON_IMPORT_PATTERN.test(content)) {
          importers.push(path.relative(ROOT, fullPath).split(path.sep).join('/'))
        }
      }
    }
  }

  walk(dir)
  return importers.sort()
}

export function readBaseline(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'))
    .sort()
}

export function diffAgainstBaseline(
  current: string[],
  baseline: string[]
): { added: string[]; removed: string[] } {
  const baselineSet = new Set(baseline)
  const currentSet = new Set(current)
  return {
    added: current.filter((file) => !baselineSet.has(file)),
    removed: baseline.filter((file) => !currentSet.has(file))
  }
}

function renderBaseline(files: string[]): string {
  return [
    '# Non-test modules under src/main/ that import `electron`.',
    '# Generated by config/scripts/check-shell-electron-ratchet.ts.',
    '# This list is a RATCHET: entries may only be removed as Electron dependencies are decoupled.',
    '# Any new Electron import fails CI.',
    '',
    ...files
  ].join('\n')
}

async function main(): Promise<void> {
  const write = process.argv.includes('--write')
  const current = scanShellElectronImporters()

  if (write) {
    writeFileSync(BASELINE_PATH, `${renderBaseline(current)}\n`)
    console.log(`[shell-electron-ratchet] wrote ${current.length} entries to ${BASELINE_PATH}`)
    return
  }

  const baseline = readBaseline(readFileSync(BASELINE_PATH, 'utf8'))
  const { added, removed } = diffAgainstBaseline(current, baseline)

  if (added.length > 0) {
    const addedLines = added.map((file) => `  + ${file}`).join('\n')
    console.error(
      `[shell-electron-ratchet] ${added.length} new module(s) in src/main/ now import electron:\n${addedLines}\n\nNew Electron imports in src/main/ are prohibited to preserve browser-as-shell parity.\nDecouple the logic behind a host port or shared capability.`
    )
    process.exitCode = 1
    return
  }

  if (removed.length > 0) {
    const removedLines = removed.map((file) => `  - ${file}`).join('\n')
    console.error(
      `[shell-electron-ratchet] ${removed.length} module(s) no longer import electron — nice.\nRefresh the baseline so the ratchet retains its tighter ceiling:\n${removedLines}\n\n  node config/scripts/check-shell-electron-ratchet.ts --write`
    )
    process.exitCode = 1
    return
  }

  console.log(`[shell-electron-ratchet] ok — ${current.length} entries, unchanged.`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main()
}
