export type GitHubTaskKind = 'issues' | 'prs'
export type GitHubMode = GitHubTaskKind | 'project'
export type GitHubPreset = 'issues' | 'my-issues' | 'prs' | 'my-prs' | 'review'
export type GitLabView = 'project' | 'todos'
export type GitLabFilter = 'opened' | 'merged' | 'closed' | 'all'
export type LinearFilter = 'assigned' | 'created' | 'all' | 'completed'
export type LinearViewMode = 'list' | 'board'
export type LinearGroupBy = 'none' | 'status' | 'assignee' | 'priority' | 'team'
export type LinearOrderBy = 'priority' | 'updated' | 'identifier'
export type LinearDisplayProperty =
  | 'state'
  | 'priority'
  | 'assignee'
  | 'team'
  | 'labels'
  | 'updated'
export type TaskSort = 'updated' | 'repository'
