import type { LinearViewsHostProps } from '@/components/task-page/linear/linear-views-host'
import type { LinearViewsHostDeps } from './linear-views-host-deps'

// Pure builders for the TaskPageLayout Linear host and create-dialog prop objects.
type LinearDialogsDeps = LinearViewsHostDeps

export function buildLinearViews(deps: LinearDialogsDeps): LinearViewsHostProps {
  return {
    selectedLinearIssue: deps.selectedLinearIssue,
    activeLinearIssueContextLabel: deps.activeLinearIssueContextLabel,
    handleUseLinearItem: deps.handleUseLinearItem,
    openRelatedLinearIssue: deps.openRelatedLinearIssue,
    closeTaskDetailPage: deps.closeTaskDetailPage,
    linearDetailSourceContext: deps.linearDetailSourceContext,
    linearStatusReady: deps.linearStatusReady,
    linearConnected: deps.linearConnected,
    setLinearConnectOpen: deps.setLinearConnectOpen,
    selectedLinearProject: deps.selectedLinearProject,
    linearProjectTab: deps.linearProjectTab,
    selectedLinearProjectDetail: deps.selectedLinearProjectDetail,
    linearProjectDetailLoading: deps.linearProjectDetailLoading,
    linearProjectDetailError: deps.linearProjectDetailError,
    linearProjectParentView: deps.linearProjectParentView,
    setSelectedLinearProject: deps.setSelectedLinearProject,
    setSelectedLinearProjectDetail: deps.setSelectedLinearProjectDetail,
    setLinearProjectTab: deps.setLinearProjectTab,
    setLinearMode: deps.setLinearMode,
    setSelectedLinearCustomView: deps.setSelectedLinearCustomView,
    setTaskResumeState: deps.setTaskResumeState,
    setLinearProjectParentView: deps.setLinearProjectParentView,
    setLinearRefreshNonce: deps.setLinearRefreshNonce,
    linearMode: deps.linearMode,
    linearProjectsError: deps.linearProjectsError,
    linearProjectsResult: deps.linearProjectsResult,
    linearProjectsLoading: deps.linearProjectsLoading,
    selectedLinearWorkspaceId: deps.selectedLinearWorkspaceId,
    openLinearProjectContext: deps.openLinearProjectContext,
    selectedLinearCustomView: deps.selectedLinearCustomView,
    linearCustomViewsError: deps.linearCustomViewsError,
    linearCustomViewsResult: deps.linearCustomViewsResult,
    linearCustomViewsLoading: deps.linearCustomViewsLoading,
    openLinearCustomViewContext: deps.openLinearCustomViewContext,
    linearCustomViewContentsError: deps.linearCustomViewContentsError,
    linearCustomViewProjectsResult: deps.linearCustomViewProjectsResult,
    linearCustomViewContentsLoading: deps.linearCustomViewContentsLoading,
    issueList: {
      toolbar: {
        activeLinearIssueContextLabel: deps.activeLinearIssueContextLabel,
        selectedLinearProject: deps.selectedLinearProject,
        setLinearProjectTab: deps.setLinearProjectTab,
        setSelectedLinearCustomView: deps.setSelectedLinearCustomView,
        setLinearProjectParentView: deps.setLinearProjectParentView,
        setTaskResumeState: deps.setTaskResumeState,
        linearMode: deps.linearMode,
        linearViewOptions: deps.linearViewOptions,
        linearViewMode: deps.linearViewMode,
        setLinearViewMode: deps.setLinearViewMode,
        linearGroupBy: deps.linearGroupBy,
        setLinearGroupBy: deps.setLinearGroupBy,
        linearGroupOptions: deps.linearGroupOptions,
        linearOrderBy: deps.linearOrderBy,
        setLinearOrderBy: deps.setLinearOrderBy,
        linearOrderOptions: deps.linearOrderOptions,
        linearDisplayPropertyOptions: deps.linearDisplayPropertyOptions,
        effectiveLinearDisplayProperties: deps.effectiveLinearDisplayProperties,
        toggleLinearDisplayProperty: deps.toggleLinearDisplayProperty,
        linearIssueGridStyle: deps.linearIssueGridStyle
      },
      empty: {
        activeLinearIssueError: deps.activeLinearIssueError,
        activeLinearIssueLoading: deps.activeLinearIssueLoading,
        activeLinearIssues: deps.activeLinearIssues,
        activeLinearIssueHasCollectionError: deps.activeLinearIssueHasCollectionError,
        linearMode: deps.linearMode,
        linearSearchActive: deps.linearSearchActive,
        activeLinearIssueContextLabel: deps.activeLinearIssueContextLabel,
        linearAttributeFilter: deps.linearAttributeFilter,
        filteredLinearIssues: deps.filteredLinearIssues,
        linearIssuesHasMore: deps.linearIssuesHasMore,
        setLinearIssueLimit: deps.setLinearIssueLimit
      },
      board: {
        linearBoardSections: deps.linearBoardSections,
        handleLinearBoardDragOver: deps.handleLinearBoardDragOver,
        handleLinearBoardDrop: deps.handleLinearBoardDrop,
        linearBoardDragOverKey: deps.linearBoardDragOverKey,
        selectedLinearIssueId: deps.selectedLinearIssueId,
        linearBoardDraggingIssueId: deps.linearBoardDraggingIssueId,
        linearBoardUpdatingIssueIds: deps.linearBoardUpdatingIssueIds,
        selectedLinearWorkspaceId: deps.selectedLinearWorkspaceId,
        linearIssueAttachmentIndex: deps.linearIssueAttachmentIndex,
        linearStatusBoardEnabled: deps.linearStatusBoardEnabled,
        handleLinearBoardCardDragStart: deps.handleLinearBoardCardDragStart,
        setLinearBoardDraggingIssueId: deps.setLinearBoardDraggingIssueId,
        setLinearBoardDragOverKey: deps.setLinearBoardDragOverKey,
        openLinearDetailPage: deps.openLinearDetailPage,
        effectiveLinearDisplayProperties: deps.effectiveLinearDisplayProperties,
        handleOpenOrUseLinearItem: deps.handleOpenOrUseLinearItem,
        linearTaskSourceContext: deps.linearTaskSourceContext
      },
      list: {
        linearIssueListRows: deps.linearIssueListRows,
        selectedLinearIssueId: deps.selectedLinearIssueId,
        selectedLinearWorkspaceId: deps.selectedLinearWorkspaceId,
        linearIssueAttachmentIndex: deps.linearIssueAttachmentIndex,
        openLinearDetailPage: deps.openLinearDetailPage,
        linearIssueGridStyle: deps.linearIssueGridStyle,
        effectiveLinearDisplayProperties: deps.effectiveLinearDisplayProperties,
        linearTaskSourceContext: deps.linearTaskSourceContext,
        handleOpenOrUseLinearItem: deps.handleOpenOrUseLinearItem
      },
      linearViewMode: deps.linearViewMode,
      selectedLinearProject: deps.selectedLinearProject,
      linearProjectTab: deps.linearProjectTab,
      selectedLinearCustomView: deps.selectedLinearCustomView,
      linearProjectIssuesResult: deps.linearProjectIssuesResult,
      linearCustomViewIssuesResult: deps.linearCustomViewIssuesResult,
      linearIssues: deps.linearIssues,
      showLinearEmptyFilteredLoadMore: deps.showLinearEmptyFilteredLoadMore,
      handleLinearEmptyFilteredLoadMore: deps.handleLinearEmptyFilteredLoadMore,
      activeLinearIssueLoading: deps.activeLinearIssueLoading,
      showLinearIssuePagination: deps.showLinearIssuePagination,
      visibleLinearIssuePage: deps.visibleLinearIssuePage,
      linearIssueTotalPages: deps.linearIssueTotalPages,
      activeLinearIssueLoadingTargetPage: deps.activeLinearIssueLoadingTargetPage,
      handleLinearIssuePageChange: deps.handleLinearIssuePageChange,
      pagedLinearIssuesCount: deps.pagedLinearIssues.length
    }
  }
}
