import type { TaskPageSourceToolbarProps } from '@/components/task-page/chrome/task-page-source-toolbar'
import type { TaskPageGithubItemFiltersProps } from '@/components/task-page/chrome/task-page-github-item-filters'
import type { TaskPageJiraFiltersProps } from '@/components/task-page/chrome/task-page-jira-filters'
import type { TaskPageGitlabFiltersProps } from '@/components/task-page/chrome/task-page-gitlab-filters'
import type { TaskPageConnectDialogsProps } from '@/components/task-page/dialogs/task-page-connect-dialogs'
import type { TaskPageSectionsGitlabListDeps } from './task-page-sections-gitlab-list-deps'
import type { TaskPageGithubModeBarProps } from '@/components/task-page/chrome/task-page-github-mode-bar'
import type { TaskPageLinearFiltersProps } from '@/components/task-page/chrome/task-page-linear-filters'
import type { NewGithubIssueDialogProps } from '@/components/task-page/dialogs/new-github-issue-dialog'
import type { NewLinearProjectDialogProps } from '@/components/task-page/dialogs/new-linear-project-dialog'
import type { NewLinearIssueDialogProps } from '@/components/task-page/dialogs/new-linear-issue-dialog'
import type { NewJiraIssueDialogProps } from '@/components/task-page/dialogs/new-jira-issue-dialog'

export type TaskPageSectionsProps = TaskPageSectionsGitlabListDeps & ListChromeDeps & DialogsDeps

type ListChromeDeps = {
  closeTaskPage: TaskPageSourceToolbarProps['closeTaskPage']
  visibleSourceOptions: TaskPageSourceToolbarProps['visibleSourceOptions']
  taskSource: TaskPageSourceToolbarProps['taskSource']
  taskSourceAvailabilityNoticeByProvider: TaskPageSourceToolbarProps['taskSourceAvailabilityNoticeByProvider']
  taskSourceManuallyChangedRef: TaskPageSourceToolbarProps['taskSourceManuallyChangedRef']
  openTaskPage: TaskPageSourceToolbarProps['openTaskPage']
  updateSettings: TaskPageSourceToolbarProps['updateSettings']
  taskSourceContextSummary: TaskPageSourceToolbarProps['taskSourceContextSummary']
  linearWorkspaces: TaskPageSourceToolbarProps['linearWorkspaces']
  selectedLinearWorkspaceId: TaskPageSourceToolbarProps['selectedLinearWorkspaceId']
  linearTeamOptions: TaskPageSourceToolbarProps['linearTeamOptions']
  linearTeamSelection: TaskPageSourceToolbarProps['linearTeamSelection']
  defaultLinearTeamSelection: TaskPageSourceToolbarProps['defaultLinearTeamSelection']
  handleLinearWorkspaceChange: TaskPageSourceToolbarProps['onLinearWorkspaceChange']
  handleLinearTeamSelectionChange: TaskPageSourceToolbarProps['onLinearTeamSelectionChange']
  handleLinearScopeOpen: TaskPageSourceToolbarProps['onLinearScopeOpen']
  selectedLinearTeamForExternalLink: TaskPageSourceToolbarProps['selectedLinearTeamForExternalLink']
  jiraSites: TaskPageSourceToolbarProps['jiraSites']
  selectedJiraSiteId: TaskPageSourceToolbarProps['selectedJiraSiteId']
  selectJiraSite: TaskPageSourceToolbarProps['selectJiraSite']
  setSelectedJiraIssueKey: TaskPageSourceToolbarProps['setSelectedJiraIssueKey']
  setSelectedJiraIssueFallback: TaskPageSourceToolbarProps['setSelectedJiraIssueFallback']
  setJiraIssues: TaskPageSourceToolbarProps['setJiraIssues']
  setJiraError: TaskPageSourceToolbarProps['setJiraError']
  setJiraLoading: TaskPageSourceToolbarProps['setJiraLoading']
  taskSourceAvailabilityNotice: TaskPageSourceToolbarProps['taskSourceAvailabilityNotice']

  projectModeVisible: TaskPageGithubModeBarProps['projectModeVisible']
  githubModeButtons: TaskPageGithubModeBarProps['githubModeButtons']
  githubMode: TaskPageGithubModeBarProps['githubMode']
  activeGithubTaskKind: TaskPageGithubModeBarProps['activeGithubTaskKind']
  setGithubMode: TaskPageGithubModeBarProps['setGithubMode']
  handleSelectGithubTaskKind: TaskPageGithubModeBarProps['handleSelectGithubTaskKind']
  taskPickerGroups: TaskPageGithubModeBarProps['taskPickerGroups']
  repoSelection: TaskPageGithubModeBarProps['repoSelection']
  getTaskPickerRepoHostLabel: TaskPageGithubModeBarProps['getTaskPickerRepoHostLabel']
  eligibleRepos: TaskPageGithubModeBarProps['eligibleRepos']
  setRepoSelection: TaskPageGithubModeBarProps['setRepoSelection']
  taskPickerRepos: TaskPageGithubModeBarProps['taskPickerRepos']
  selectedGitHubRepoExternalLink: TaskPageGithubModeBarProps['selectedGitHubRepoExternalLink']

  activeTaskPreset: TaskPageGithubItemFiltersProps['activeTaskPreset']
  setTaskSearchInput: TaskPageGithubItemFiltersProps['setTaskSearchInput']
  setAppliedTaskSearch: TaskPageGithubItemFiltersProps['setAppliedTaskSearch']
  setActiveTaskPreset: TaskPageGithubItemFiltersProps['setActiveTaskPreset']
  setTaskRefreshNonce: TaskPageGithubItemFiltersProps['setTaskRefreshNonce']
  handleSetDefaultTaskPreset: TaskPageGithubItemFiltersProps['handleSetDefaultTaskPreset']
  appliedTaskQuery: TaskPageGithubItemFiltersProps['appliedTaskQuery']
  loadedGitHubAuthorLogins: TaskPageGithubItemFiltersProps['loadedGitHubAuthorLogins']
  primaryGithubFilterSlug: TaskPageGithubItemFiltersProps['primaryGithubFilterSlug']
  settings: TaskPageGithubItemFiltersProps['settings']
  applyPRFilterChange: TaskPageGithubItemFiltersProps['applyPRFilterChange']
  taskSearchInputRef: TaskPageGithubItemFiltersProps['taskSearchInputRef']
  taskSearchInput: TaskPageGithubItemFiltersProps['taskSearchInput']
  handleTaskSearchChange: TaskPageGithubItemFiltersProps['handleTaskSearchChange']
  handleTaskSearchKeyDown: TaskPageGithubItemFiltersProps['handleTaskSearchKeyDown']
  appliedTaskSearch: TaskPageGithubItemFiltersProps['appliedTaskSearch']
  handleResetGithubTaskSearch: TaskPageGithubItemFiltersProps['handleResetGithubTaskSearch']
  newIssueTargetRepo: TaskPageGithubItemFiltersProps['newIssueTargetRepo']
  handleRefreshGithubTasks: TaskPageGithubItemFiltersProps['handleRefreshGithubTasks']
  githubTasksBusy: TaskPageGithubItemFiltersProps['githubTasksBusy']
  setIssueSourcePreference: TaskPageGithubItemFiltersProps['setIssueSourcePreference']

  linearModeOptions: TaskPageLinearFiltersProps['linearModeOptions']
  selectLinearMode: TaskPageLinearFiltersProps['selectLinearMode']
  availableTeams: TaskPageLinearFiltersProps['availableTeams']
  setNewLinearProjectName: TaskPageLinearFiltersProps['setNewLinearProjectName']
  setNewLinearProjectDescription: TaskPageLinearFiltersProps['setNewLinearProjectDescription']
  setNewLinearProjectContent: TaskPageLinearFiltersProps['setNewLinearProjectContent']
  setNewLinearProjectTeamId: TaskPageLinearFiltersProps['setNewLinearProjectTeamId']
  setNewLinearProjectLeadId: TaskPageLinearFiltersProps['setNewLinearProjectLeadId']
  setNewLinearProjectMemberIds: TaskPageLinearFiltersProps['setNewLinearProjectMemberIds']
  setNewLinearProjectLabelIds: TaskPageLinearFiltersProps['setNewLinearProjectLabelIds']
  setNewLinearProjectPriority: TaskPageLinearFiltersProps['setNewLinearProjectPriority']
  setNewLinearProjectStartDate: TaskPageLinearFiltersProps['setNewLinearProjectStartDate']
  setNewLinearProjectTargetDate: TaskPageLinearFiltersProps['setNewLinearProjectTargetDate']
  setNewLinearProjectOpen: TaskPageLinearFiltersProps['setNewLinearProjectOpen']
  setNewLinearIssueTitle: TaskPageLinearFiltersProps['setNewLinearIssueTitle']
  setNewLinearIssueBody: TaskPageLinearFiltersProps['setNewLinearIssueBody']
  setNewLinearIssueTeamId: TaskPageLinearFiltersProps['setNewLinearIssueTeamId']
  setNewLinearIssueProjectId: TaskPageLinearFiltersProps['setNewLinearIssueProjectId']
  setNewLinearIssueOpen: TaskPageLinearFiltersProps['setNewLinearIssueOpen']
  linearLoading: TaskPageLinearFiltersProps['linearLoading']
  linearProjectsLoading: TaskPageLinearFiltersProps['linearProjectsLoading']
  linearProjectDetailLoading: TaskPageLinearFiltersProps['linearProjectDetailLoading']
  linearCustomViewsLoading: TaskPageLinearFiltersProps['linearCustomViewsLoading']
  linearCustomViewContentsLoading: TaskPageLinearFiltersProps['linearCustomViewContentsLoading']
  showLinearAttributeFilters: TaskPageLinearFiltersProps['showLinearAttributeFilters']
  applyLinearAttributeFilter: TaskPageLinearFiltersProps['applyLinearAttributeFilter']
  linearAttributeFilterWorkspaceId: TaskPageLinearFiltersProps['linearAttributeFilterWorkspaceId']
  linearAttributePrimaryTeam: TaskPageLinearFiltersProps['linearAttributePrimaryTeam']
  linearTaskSourceContext: TaskPageLinearFiltersProps['linearTaskSourceContext']
  linearSearchInput: TaskPageLinearFiltersProps['linearSearchInput']
  setLinearSearchInput: TaskPageLinearFiltersProps['setLinearSearchInput']
  setAppliedLinearSearch: TaskPageLinearFiltersProps['setAppliedLinearSearch']
  linearProjectSearchInput: TaskPageLinearFiltersProps['linearProjectSearchInput']
  setLinearProjectSearchInput: TaskPageLinearFiltersProps['setLinearProjectSearchInput']
  setAppliedLinearProjectSearch: TaskPageLinearFiltersProps['setAppliedLinearProjectSearch']

  jiraPresets: TaskPageJiraFiltersProps['jiraPresets']
  activeJiraPreset: TaskPageJiraFiltersProps['activeJiraPreset']
  setJiraSearchInput: TaskPageJiraFiltersProps['setJiraSearchInput']
  setAppliedJiraSearch: TaskPageJiraFiltersProps['setAppliedJiraSearch']
  setActiveJiraPreset: TaskPageJiraFiltersProps['setActiveJiraPreset']
  setJiraRefreshNonce: TaskPageJiraFiltersProps['setJiraRefreshNonce']
  sortedAvailableJiraProjects: TaskPageJiraFiltersProps['sortedAvailableJiraProjects']
  setNewJiraIssueTitle: TaskPageJiraFiltersProps['setNewJiraIssueTitle']
  setNewJiraIssueBody: TaskPageJiraFiltersProps['setNewJiraIssueBody']
  setNewJiraIssueProjectId: TaskPageJiraFiltersProps['setNewJiraIssueProjectId']
  setNewJiraIssueProjectQuery: TaskPageJiraFiltersProps['setNewJiraIssueProjectQuery']
  setNewJiraIssueProjectCommandValue: TaskPageJiraFiltersProps['setNewJiraIssueProjectCommandValue']
  setNewJiraIssueTypeId: TaskPageJiraFiltersProps['setNewJiraIssueTypeId']
  setNewJiraIssueOpen: TaskPageJiraFiltersProps['setNewJiraIssueOpen']
  jiraProjectsLoading: TaskPageJiraFiltersProps['jiraProjectsLoading']

  gitlabView: TaskPageGitlabFiltersProps['gitlabView']
  setGitlabView: TaskPageGitlabFiltersProps['setGitlabView']
  gitLabIssueFilters: TaskPageGitlabFiltersProps['gitLabIssueFilters']
  gitLabMRFilters: TaskPageGitlabFiltersProps['gitLabMRFilters']
  activeGitlabFilter: TaskPageGitlabFiltersProps['activeGitlabFilter']
  setGitlabFilter: TaskPageGitlabFiltersProps['setGitlabFilter']
  setGitlabRefreshNonce: TaskPageGitlabFiltersProps['setGitlabRefreshNonce']
  gitlabTodosLoading: TaskPageGitlabFiltersProps['gitlabTodosLoading']
}

type DialogsDeps = {
  newIssueOpen: NewGithubIssueDialogProps['newIssueOpen']
  newIssueSubmitting: NewGithubIssueDialogProps['newIssueSubmitting']
  setNewIssueOpen: NewGithubIssueDialogProps['setNewIssueOpen']
  handleCreateNewIssue: NewGithubIssueDialogProps['handleCreateNewIssue']
  newIssueTargetRepo: NewGithubIssueDialogProps['newIssueTargetRepo']
  setNewIssueRepoId: NewGithubIssueDialogProps['setNewIssueRepoId']
  setNewIssueLabels: NewGithubIssueDialogProps['setNewIssueLabels']
  setNewIssueAssignees: NewGithubIssueDialogProps['setNewIssueAssignees']
  newIssueTitle: NewGithubIssueDialogProps['newIssueTitle']
  setNewIssueTitle: NewGithubIssueDialogProps['setNewIssueTitle']
  newIssueBody: NewGithubIssueDialogProps['newIssueBody']
  setNewIssueBody: NewGithubIssueDialogProps['setNewIssueBody']
  newIssueRepoLabels: NewGithubIssueDialogProps['newIssueRepoLabels']
  newIssueLabels: NewGithubIssueDialogProps['newIssueLabels']
  newIssueRepoAssignees: NewGithubIssueDialogProps['newIssueRepoAssignees']
  newIssueAssignees: NewGithubIssueDialogProps['newIssueAssignees']
  submitShortcutLabel: NewGithubIssueDialogProps['submitShortcutLabel']

  newLinearProjectOpen: NewLinearProjectDialogProps['newLinearProjectOpen']
  newLinearProjectSubmitting: NewLinearProjectDialogProps['newLinearProjectSubmitting']
  setNewLinearProjectOpen: NewLinearProjectDialogProps['setNewLinearProjectOpen']
  handleCreateNewLinearProject: NewLinearProjectDialogProps['handleCreateNewLinearProject']
  newLinearProjectTargetTeam: NewLinearProjectDialogProps['newLinearProjectTargetTeam']
  setNewLinearProjectTeamId: NewLinearProjectDialogProps['setNewLinearProjectTeamId']
  newLinearProjectName: NewLinearProjectDialogProps['newLinearProjectName']
  setNewLinearProjectName: NewLinearProjectDialogProps['setNewLinearProjectName']
  newLinearProjectDescription: NewLinearProjectDialogProps['newLinearProjectDescription']
  setNewLinearProjectDescription: NewLinearProjectDialogProps['setNewLinearProjectDescription']
  newLinearProjectContent: NewLinearProjectDialogProps['newLinearProjectContent']
  setNewLinearProjectContent: NewLinearProjectDialogProps['setNewLinearProjectContent']
  newLinearProjectPriority: NewLinearProjectDialogProps['newLinearProjectPriority']
  setNewLinearProjectPriority: NewLinearProjectDialogProps['setNewLinearProjectPriority']
  newLinearProjectMembers: NewLinearProjectDialogProps['newLinearProjectMembers']
  newLinearProjectLeadId: NewLinearProjectDialogProps['newLinearProjectLeadId']
  setNewLinearProjectLeadId: NewLinearProjectDialogProps['setNewLinearProjectLeadId']
  newLinearProjectMemberIds: NewLinearProjectDialogProps['newLinearProjectMemberIds']
  setNewLinearProjectMemberIds: NewLinearProjectDialogProps['setNewLinearProjectMemberIds']
  newLinearProjectLabelIds: NewLinearProjectDialogProps['newLinearProjectLabelIds']
  setNewLinearProjectLabelIds: NewLinearProjectDialogProps['setNewLinearProjectLabelIds']
  newLinearProjectLabels: NewLinearProjectDialogProps['newLinearProjectLabels']
  newLinearProjectStartDate: NewLinearProjectDialogProps['newLinearProjectStartDate']
  setNewLinearProjectStartDate: NewLinearProjectDialogProps['setNewLinearProjectStartDate']
  newLinearProjectTargetDate: NewLinearProjectDialogProps['newLinearProjectTargetDate']
  setNewLinearProjectTargetDate: NewLinearProjectDialogProps['setNewLinearProjectTargetDate']

  newLinearIssueOpen: NewLinearIssueDialogProps['newLinearIssueOpen']
  newLinearIssueSubmitting: NewLinearIssueDialogProps['newLinearIssueSubmitting']
  setNewLinearIssueOpen: NewLinearIssueDialogProps['setNewLinearIssueOpen']
  handleCreateNewLinearIssue: NewLinearIssueDialogProps['handleCreateNewLinearIssue']
  newLinearIssueTargetTeam: NewLinearIssueDialogProps['newLinearIssueTargetTeam']
  newLinearIssueTeamId: NewLinearIssueDialogProps['newLinearIssueTeamId']
  setNewLinearIssueTeamId: NewLinearIssueDialogProps['setNewLinearIssueTeamId']
  newLinearIssueTitle: NewLinearIssueDialogProps['newLinearIssueTitle']
  setNewLinearIssueTitle: NewLinearIssueDialogProps['setNewLinearIssueTitle']
  newLinearIssueBody: NewLinearIssueDialogProps['newLinearIssueBody']
  setNewLinearIssueBody: NewLinearIssueDialogProps['setNewLinearIssueBody']
  newLinearStates: NewLinearIssueDialogProps['newLinearStates']
  newLinearIssueStateId: NewLinearIssueDialogProps['newLinearIssueStateId']
  setNewLinearIssueStateId: NewLinearIssueDialogProps['setNewLinearIssueStateId']
  newLinearMembers: NewLinearIssueDialogProps['newLinearMembers']
  newLinearIssueAssigneeId: NewLinearIssueDialogProps['newLinearIssueAssigneeId']
  setNewLinearIssueAssigneeId: NewLinearIssueDialogProps['setNewLinearIssueAssigneeId']
  newLinearIssuePriority: NewLinearIssueDialogProps['newLinearIssuePriority']
  setNewLinearIssuePriority: NewLinearIssueDialogProps['setNewLinearIssuePriority']
  newLinearIssueProjects: NewLinearIssueDialogProps['newLinearIssueProjects']
  newLinearIssueProjectId: NewLinearIssueDialogProps['newLinearIssueProjectId']
  setNewLinearIssueProjectId: NewLinearIssueDialogProps['setNewLinearIssueProjectId']
  newLinearIssueProjectsLoading: NewLinearIssueDialogProps['newLinearIssueProjectsLoading']
  newLinearIssueLabelIds: NewLinearIssueDialogProps['newLinearIssueLabelIds']
  setNewLinearIssueLabelIds: NewLinearIssueDialogProps['setNewLinearIssueLabelIds']
  newLinearLabels: NewLinearIssueDialogProps['newLinearLabels']

  newJiraIssueOpen: NewJiraIssueDialogProps['newJiraIssueOpen']
  newJiraIssueSubmitting: NewJiraIssueDialogProps['newJiraIssueSubmitting']
  setNewJiraIssueOpen: NewJiraIssueDialogProps['setNewJiraIssueOpen']
  handleCreateNewJiraIssue: NewJiraIssueDialogProps['handleCreateNewJiraIssue']
  newJiraIssueTargetProject: NewJiraIssueDialogProps['newJiraIssueTargetProject']
  newJiraIssueProjectComboboxOpen: NewJiraIssueDialogProps['newJiraIssueProjectComboboxOpen']
  handleNewJiraIssueProjectComboboxOpenChange: NewJiraIssueDialogProps['handleNewJiraIssueProjectComboboxOpenChange']
  handleNewJiraIssueProjectTriggerKeyDown: NewJiraIssueDialogProps['handleNewJiraIssueProjectTriggerKeyDown']
  includeJiraSiteNameInProjectLabel: NewJiraIssueDialogProps['includeJiraSiteNameInProjectLabel']
  newJiraIssueProjectCommandValue: NewJiraIssueDialogProps['newJiraIssueProjectCommandValue']
  setNewJiraIssueProjectCommandValue: NewJiraIssueDialogProps['setNewJiraIssueProjectCommandValue']
  newJiraIssueProjectSearchInputRef: NewJiraIssueDialogProps['newJiraIssueProjectSearchInputRef']
  newJiraIssueProjectQuery: NewJiraIssueDialogProps['newJiraIssueProjectQuery']
  setNewJiraIssueProjectQuery: NewJiraIssueDialogProps['setNewJiraIssueProjectQuery']
  filteredNewJiraIssueProjects: NewJiraIssueDialogProps['filteredNewJiraIssueProjects']
  newJiraIssueTargetProjectSelectionKey: NewJiraIssueDialogProps['newJiraIssueTargetProjectSelectionKey']
  handleNewJiraIssueProjectSelect: NewJiraIssueDialogProps['handleNewJiraIssueProjectSelect']
  newJiraIssueTypeId: NewJiraIssueDialogProps['newJiraIssueTypeId']
  newJiraIssueTargetType: NewJiraIssueDialogProps['newJiraIssueTargetType']
  setNewJiraIssueTypeId: NewJiraIssueDialogProps['setNewJiraIssueTypeId']
  jiraIssueTypesLoading: NewJiraIssueDialogProps['jiraIssueTypesLoading']
  availableJiraIssueTypes: NewJiraIssueDialogProps['availableJiraIssueTypes']
  jiraCreateFieldsLoading: NewJiraIssueDialogProps['jiraCreateFieldsLoading']
  jiraCreateFieldsError: NewJiraIssueDialogProps['jiraCreateFieldsError']
  visibleJiraCreateFields: NewJiraIssueDialogProps['visibleJiraCreateFields']
  newJiraIssueCustomFieldValues: NewJiraIssueDialogProps['newJiraIssueCustomFieldValues']
  setNewJiraIssueCustomFieldValues: NewJiraIssueDialogProps['setNewJiraIssueCustomFieldValues']
  hasMissingJiraCreateField: NewJiraIssueDialogProps['hasMissingJiraCreateField']

  linearConnectOpen: TaskPageConnectDialogsProps['linearConnectOpen']
  newJiraIssueTitle: NewJiraIssueDialogProps['newJiraIssueTitle']
  setNewJiraIssueTitle: NewJiraIssueDialogProps['setNewJiraIssueTitle']
  newJiraIssueBody: NewJiraIssueDialogProps['newJiraIssueBody']
  setNewJiraIssueBody: NewJiraIssueDialogProps['setNewJiraIssueBody']
}
