import type { TaskPageConnectDialogsProps } from '@/components/task-page/dialogs/task-page-connect-dialogs'
import type { GithubDetailHostProps } from '@/components/task-page/github/github-detail-host'
import type { GithubWorkItemTableProps } from '@/components/task-page/github/github-work-item-table'
import type { GitlabWorkItemListProps } from '@/components/task-page/gitlab/gitlab-work-item-list'
import type { JiraIssueListHostProps } from '@/components/task-page/jira/jira-issue-list-host'
import type { TaskPageGitlabFiltersProps } from '@/components/task-page/chrome/task-page-gitlab-filters'
import type { NewGithubIssueDialogProps } from '@/components/task-page/dialogs/new-github-issue-dialog'
import type { LinearViewsHostProps } from '@/components/task-page/linear/linear-views-host'

export type TaskPageSectionsGitlabListDeps = {
  gitlabDialogItem: TaskPageConnectDialogsProps['gitlabDialogItem']
  gitlabDialogRepo: TaskPageConnectDialogsProps['gitlabDialogRepo']
  gitlabDialogSourceContext: TaskPageConnectDialogsProps['gitlabDialogSourceContext']
  setGitlabDialogItem: TaskPageConnectDialogsProps['setGitlabDialogItem']
  handleUseGitLabItem: TaskPageConnectDialogsProps['handleUseGitLabItem']
  linearConnectOpen: TaskPageConnectDialogsProps['linearConnectOpen']
  setLinearConnectOpen: TaskPageConnectDialogsProps['setLinearConnectOpen']
  selectedLinearWorkspace: TaskPageConnectDialogsProps['selectedLinearWorkspace']
  handleLinearAccessConnected: TaskPageConnectDialogsProps['handleLinearAccessConnected']
  jiraConnectOpen: TaskPageConnectDialogsProps['jiraConnectOpen']
  setJiraConnectOpen: TaskPageConnectDialogsProps['setJiraConnectOpen']

  gitlabView: TaskPageGitlabFiltersProps['gitlabView']
  gitlabError: GitlabWorkItemListProps['gitlabError']
  gitlabLoading: GitlabWorkItemListProps['gitlabLoading']
  gitlabItems: GitlabWorkItemListProps['gitlabItems']
  displayedGitLabItems: GitlabWorkItemListProps['displayedGitLabItems']
  gitlabEmptyState: GitlabWorkItemListProps['gitlabEmptyState']
  openGitLabDetailPage: GitlabWorkItemListProps['openGitLabDetailPage']
  gitlabIssuePage: GitlabWorkItemListProps['gitlabIssuePage']
  gitlabIssueTotalPages: GitlabWorkItemListProps['gitlabIssueTotalPages']
  gitlabIssueLoadingTargetPage: GitlabWorkItemListProps['gitlabIssueLoadingTargetPage']
  setGitlabIssueLoadingTargetPage: (page: number) => void
  setGitlabIssuePage: (page: number) => void

  dialogWorkItem: GithubDetailHostProps['dialogWorkItem'] | null
  dialogInitialTab: GithubDetailHostProps['dialogInitialTab']
  dialogRepoPath: GithubDetailHostProps['dialogRepoPath']
  dialogSourceContext: GithubDetailHostProps['dialogSourceContext']
  setDialogWorkItem: GithubDetailHostProps['setDialogWorkItem']
  handleUseWorkItem: GithubDetailHostProps['handleUseWorkItem']
  handleDialogReviewRequestsChange: GithubDetailHostProps['handleDialogReviewRequestsChange']
  closeTaskDetailPage: GithubDetailHostProps['closeTaskDetailPage']

  githubListScrollRef: GithubWorkItemTableProps['githubListScrollRef']
  githubResumeContextKey: GithubWorkItemTableProps['githubResumeContextKey']
  currentPageRef: GithubWorkItemTableProps['currentPageRef']
  pendingGithubScrollRestoreRef: GithubWorkItemTableProps['pendingGithubScrollRestoreRef']
  githubListScrollTopRef: GithubWorkItemTableProps['githubListScrollTopRef']
  taskListPositionRef: GithubWorkItemTableProps['taskListPositionRef']
  githubTaskGridClass: GithubWorkItemTableProps['githubTaskGridClass']
  activeGithubTaskKind: GithubWorkItemTableProps['activeGithubTaskKind']
  showPRManagementColumns: GithubWorkItemTableProps['showPRManagementColumns']
  tasksError: GithubWorkItemTableProps['tasksError']
  githubUnavailable: GithubWorkItemTableProps['githubUnavailable']
  failedCount: GithubWorkItemTableProps['failedCount']
  selectedRepos: GithubWorkItemTableProps['selectedRepos']
  perRepoSourceState: GithubWorkItemTableProps['perRepoSourceState']
  handleRetryIssuesFetch: GithubWorkItemTableProps['handleRetryIssuesFetch']
  tasksLoading: GithubWorkItemTableProps['tasksLoading']
  retryingSourceKeys: GithubWorkItemTableProps['retryingSourceKeys']
  unresolvedSourceRepos: GithubWorkItemTableProps['unresolvedSourceRepos']
  showGitHubTaskSkeletons: GithubWorkItemTableProps['showGitHubTaskSkeletons']
  filteredWorkItems: GithubWorkItemTableProps['filteredWorkItems']
  softHiddenVisibleCount: GithubWorkItemTableProps['softHiddenVisibleCount']
  totalPages: GithubWorkItemTableProps['totalPages']
  githubEmptyState: GithubWorkItemTableProps['githubEmptyState']
  repoMap: GithubWorkItemTableProps['repoMap']
  allWorktrees: GithubWorkItemTableProps['allWorktrees']
  openGitHubDetailPage: GithubWorkItemTableProps['openGitHubDetailPage']
  githubWorkItemMutation: GithubWorkItemTableProps['githubWorkItemMutation']
  ensurePRChecksLoaded: GithubWorkItemTableProps['ensurePRChecksLoaded']
  handleOpenOrUseGitHubWorkItem: GithubWorkItemTableProps['handleOpenOrUseGitHubWorkItem']
  newIssueRepoId: NewGithubIssueDialogProps['newIssueRepoId']
  currentPage: GithubWorkItemTableProps['currentPage']
  loadingTargetPage: GithubWorkItemTableProps['loadingTargetPage']
  pages: GithubWorkItemTableProps['pages']
  handleLoadNextPage: GithubWorkItemTableProps['handleLoadNextPage']
  setCurrentPage: GithubWorkItemTableProps['setCurrentPage']

  jiraLoading: JiraIssueListHostProps['jiraLoading']
  jiraStatusReady: JiraIssueListHostProps['jiraStatusReady']
  jiraConnected: JiraIssueListHostProps['jiraConnected']
  hideTaskSource: JiraIssueListHostProps['hideTaskSource']
  displayedJiraIssues: JiraIssueListHostProps['displayedJiraIssues']
  jiraOrderDirection: JiraIssueListHostProps['jiraOrderDirection']
  handleJiraSort: JiraIssueListHostProps['handleJiraSort']
  jiraOrderBy: JiraIssueListHostProps['jiraOrderBy']
  jiraStatusCredentialError: JiraIssueListHostProps['jiraStatusCredentialError']
  jiraError: JiraIssueListHostProps['jiraError']
  jiraErrorDetailsOpen: JiraIssueListHostProps['jiraErrorDetailsOpen']
  setJiraErrorDetailsOpen: JiraIssueListHostProps['setJiraErrorDetailsOpen']
  jiraIssues: JiraIssueListHostProps['jiraIssues']
  jiraSearchInput: JiraIssueListHostProps['jiraSearchInput']
  sortedJiraIssues: JiraIssueListHostProps['sortedJiraIssues']
  handleUseJiraItem: JiraIssueListHostProps['handleUseJiraItem']
  openJiraDetailPage: JiraIssueListHostProps['openJiraDetailPage']
  selectedJiraIssue: JiraIssueListHostProps['selectedJiraIssue']
  selectedJiraSiteId: JiraIssueListHostProps['selectedJiraSiteId']
  displayedJiraStatusOrder: JiraIssueListHostProps['displayedJiraStatusOrder']
  jiraDetailSourceContext: JiraIssueListHostProps['jiraDetailSourceContext']

  selectedLinearIssue: LinearViewsHostProps['selectedLinearIssue']
  activeLinearIssueContextLabel: LinearViewsHostProps['activeLinearIssueContextLabel']
  handleUseLinearItem: LinearViewsHostProps['handleUseLinearItem']
  openRelatedLinearIssue: LinearViewsHostProps['openRelatedLinearIssue']
  linearDetailSourceContext: LinearViewsHostProps['linearDetailSourceContext']
  linearStatusReady: LinearViewsHostProps['linearStatusReady']
  linearConnected: LinearViewsHostProps['linearConnected']
  selectedLinearProject: LinearViewsHostProps['selectedLinearProject']
  linearProjectTab: LinearViewsHostProps['linearProjectTab']
  selectedLinearProjectDetail: LinearViewsHostProps['selectedLinearProjectDetail']
  linearProjectDetailLoading: LinearViewsHostProps['linearProjectDetailLoading']
  linearProjectDetailError: LinearViewsHostProps['linearProjectDetailError']
  linearProjectParentView: LinearViewsHostProps['linearProjectParentView']
  setSelectedLinearProject: LinearViewsHostProps['setSelectedLinearProject']
  setSelectedLinearProjectDetail: LinearViewsHostProps['setSelectedLinearProjectDetail']
  setLinearProjectTab: LinearViewsHostProps['setLinearProjectTab']
  setLinearMode: LinearViewsHostProps['setLinearMode']
  setSelectedLinearCustomView: LinearViewsHostProps['setSelectedLinearCustomView']
  setTaskResumeState: LinearViewsHostProps['setTaskResumeState']
  setLinearProjectParentView: LinearViewsHostProps['setLinearProjectParentView']
  setLinearRefreshNonce: LinearViewsHostProps['setLinearRefreshNonce']
  linearMode: LinearViewsHostProps['linearMode']
  linearProjectsError: LinearViewsHostProps['linearProjectsError']
  linearProjectsResult: LinearViewsHostProps['linearProjectsResult']
  linearProjectsLoading: LinearViewsHostProps['linearProjectsLoading']
  selectedLinearWorkspaceId: LinearViewsHostProps['selectedLinearWorkspaceId']
  openLinearProjectContext: LinearViewsHostProps['openLinearProjectContext']
  selectedLinearCustomView: LinearViewsHostProps['selectedLinearCustomView']
  linearCustomViewsError: LinearViewsHostProps['linearCustomViewsError']
  linearCustomViewsResult: LinearViewsHostProps['linearCustomViewsResult']
  linearCustomViewsLoading: LinearViewsHostProps['linearCustomViewsLoading']
  openLinearCustomViewContext: LinearViewsHostProps['openLinearCustomViewContext']
  linearCustomViewContentsError: LinearViewsHostProps['linearCustomViewContentsError']
  linearCustomViewProjectsResult: LinearViewsHostProps['linearCustomViewProjectsResult']
  linearCustomViewContentsLoading: LinearViewsHostProps['linearCustomViewContentsLoading']
  linearViewOptions: LinearViewsHostProps['issueList']['toolbar']['linearViewOptions']
  linearViewMode: LinearViewsHostProps['issueList']['linearViewMode']
  setLinearViewMode: LinearViewsHostProps['issueList']['toolbar']['setLinearViewMode']
  linearGroupBy: LinearViewsHostProps['issueList']['toolbar']['linearGroupBy']
  setLinearGroupBy: LinearViewsHostProps['issueList']['toolbar']['setLinearGroupBy']
  linearGroupOptions: LinearViewsHostProps['issueList']['toolbar']['linearGroupOptions']
  linearOrderBy: LinearViewsHostProps['issueList']['toolbar']['linearOrderBy']
  setLinearOrderBy: LinearViewsHostProps['issueList']['toolbar']['setLinearOrderBy']
  linearOrderOptions: LinearViewsHostProps['issueList']['toolbar']['linearOrderOptions']
  linearDisplayPropertyOptions: LinearViewsHostProps['issueList']['toolbar']['linearDisplayPropertyOptions']
  effectiveLinearDisplayProperties: LinearViewsHostProps['issueList']['toolbar']['effectiveLinearDisplayProperties']
  toggleLinearDisplayProperty: LinearViewsHostProps['issueList']['toolbar']['toggleLinearDisplayProperty']
  linearIssueGridStyle: LinearViewsHostProps['issueList']['toolbar']['linearIssueGridStyle']
  activeLinearIssueError: LinearViewsHostProps['issueList']['empty']['activeLinearIssueError']
  activeLinearIssueLoading: LinearViewsHostProps['issueList']['empty']['activeLinearIssueLoading']
  activeLinearIssues: LinearViewsHostProps['issueList']['empty']['activeLinearIssues']
  activeLinearIssueHasCollectionError: LinearViewsHostProps['issueList']['empty']['activeLinearIssueHasCollectionError']
  linearSearchActive: LinearViewsHostProps['issueList']['empty']['linearSearchActive']
  linearAttributeFilter: LinearViewsHostProps['issueList']['empty']['linearAttributeFilter']
  filteredLinearIssues: LinearViewsHostProps['issueList']['empty']['filteredLinearIssues']
  linearIssuesHasMore: LinearViewsHostProps['issueList']['empty']['linearIssuesHasMore']
  setLinearIssueLimit: LinearViewsHostProps['issueList']['empty']['setLinearIssueLimit']
  linearBoardSections: LinearViewsHostProps['issueList']['board']['linearBoardSections']
  handleLinearBoardDragOver: LinearViewsHostProps['issueList']['board']['handleLinearBoardDragOver']
  handleLinearBoardDrop: LinearViewsHostProps['issueList']['board']['handleLinearBoardDrop']
  linearBoardDragOverKey: LinearViewsHostProps['issueList']['board']['linearBoardDragOverKey']
  selectedLinearIssueId: LinearViewsHostProps['issueList']['board']['selectedLinearIssueId']
  linearBoardDraggingIssueId: LinearViewsHostProps['issueList']['board']['linearBoardDraggingIssueId']
  linearBoardUpdatingIssueIds: LinearViewsHostProps['issueList']['board']['linearBoardUpdatingIssueIds']
  linearIssueAttachmentIndex: LinearViewsHostProps['issueList']['board']['linearIssueAttachmentIndex']
  linearStatusBoardEnabled: LinearViewsHostProps['issueList']['board']['linearStatusBoardEnabled']
  handleLinearBoardCardDragStart: LinearViewsHostProps['issueList']['board']['handleLinearBoardCardDragStart']
  setLinearBoardDraggingIssueId: LinearViewsHostProps['issueList']['board']['setLinearBoardDraggingIssueId']
  setLinearBoardDragOverKey: LinearViewsHostProps['issueList']['board']['setLinearBoardDragOverKey']
  openLinearDetailPage: LinearViewsHostProps['issueList']['board']['openLinearDetailPage']
  handleOpenOrUseLinearItem: LinearViewsHostProps['issueList']['board']['handleOpenOrUseLinearItem']
  linearTaskSourceContext: LinearViewsHostProps['issueList']['board']['linearTaskSourceContext']
  linearIssueListRows: LinearViewsHostProps['issueList']['list']['linearIssueListRows']
  linearProjectIssuesResult: LinearViewsHostProps['issueList']['linearProjectIssuesResult']
  linearCustomViewIssuesResult: LinearViewsHostProps['issueList']['linearCustomViewIssuesResult']
  linearIssues: LinearViewsHostProps['issueList']['linearIssues']
  showLinearEmptyFilteredLoadMore: LinearViewsHostProps['issueList']['showLinearEmptyFilteredLoadMore']
  handleLinearEmptyFilteredLoadMore: LinearViewsHostProps['issueList']['handleLinearEmptyFilteredLoadMore']
  showLinearIssuePagination: LinearViewsHostProps['issueList']['showLinearIssuePagination']
  visibleLinearIssuePage: LinearViewsHostProps['issueList']['visibleLinearIssuePage']
  linearIssueTotalPages: LinearViewsHostProps['issueList']['linearIssueTotalPages']
  activeLinearIssueLoadingTargetPage: LinearViewsHostProps['issueList']['activeLinearIssueLoadingTargetPage']
  handleLinearIssuePageChange: LinearViewsHostProps['issueList']['handleLinearIssuePageChange']
  pagedLinearIssues: LinearViewsHostProps['issueList']['pagedLinearIssuesCount'] extends number
    ? { length: number }
    : never
}
